### ISSUE TITLE
Not getting click event after scroll

### ISSUE THREAD

**Issue by desaibijal** [Zardozz/FixedHeaderTableLayout#2]
**Describe the bug**
 I want to handle click event of every row but after scroll i am not gettiing position

**To Reproduce**

**Expected behavior**

**Screenshots**

**Stacktrace**
If applicable, add the stacktrace you encountered.

**Code for a Minimum Reproducible example**
To assist investigation a Minimum Reproducible example App should be included.

**Tools:**
 - `FixedHeaderTableLayout` version: [e.g. 0.0.0.1]
 - Android version: [e.g. 11]

**Additional context**

**Comment by Zardozz** [comment]
As per the documentation on the feature todo list on the main page "Nothing is clickable in the table yet."

I'm working on this feature but have not completed it yet.

**Comment by yaugenka** [comment]
The position gets shifted exactly by the number of scrolled rows. Is their any hack or workaround solution to get the correct position? This thing is highly wanted!

**Comment by Zardozz** [comment]
I had a draft version working, but it needed some improvement to Motion Event handling, which I've done but not tested yet, so nearly there. The clicks are current getting through just at the wrong location because of the way this scales and pans it's children, the motion Events need to be mapped to the canvas matrix. Hopefully I've release a version with working clicks soon.

**Comment by yaugenka** [comment]
I can help testing it. Where can I get it from?

**Comment by yaugenka** [comment]
Have managed to fix it myself. See the pull request #5.
PS: Coding it in Java was not fun at all. I wish the project was in Kotlin.

**Comment by Zardozz** [comment]
Fixed in commit https://github.com/Zardozz/FixedHeaderTableLayout/commit/4e2cf4f6a2d0b9d4438e94358bf33f8f08461324 

Will be released soon as 0.0.0.3

PS There are too many issues with the Kotlin language to make it worthwhile using, even google mostly use Java for their own libraries. It's not worth learning as well and google will probably drop it at some point as they do a lot with various projects.

**Comment by yaugenka** [comment]
Here is [a fix](https://github.com/yaugenka/FixedHeaderTableLayout/commit/e91058ac60531c6efaebcef202348dbc10da7e4a) for the `onInterceptTouchEvent` solution. You can take a look if you wish. In my point of view this solution is much simpler and hence less error prone than having custom handlers for each MotionEvent action.

**Comment by Zardozz** [comment]
The move to custom Handlers was due to the available GestureDetector also intercepting other gestures that actually would be more useful if available to the children views.

**Comment by Zardozz** [comment]
Your updated fix using a `OnTouchListener` still has the possibility of a child stealing Motion Events that are needed for the scale and scroll functionality.

If you are interested reading https://stackoverflow.com/a/22490810/2373819 should help understand why doing it in an override of `dispatchTouchEvent()` is a better solution (Note the FixedHeaderTableLayout is a ViewGroup)

The other difference as mentioned earlier that handling the low level events directly for scroll means I steal as little as possible (ScaleGestureDetector is used because that only steals scale related events)

**Comment by yaugenka** [comment]
I read that post when working on the fix.
> The difference is that `dispatchTouchEvent` is dispatching MotionEvents and `onInterceptTouchEvent` tells if it should intercept (not dispatching the MotionEvent to children) or not (dispatching to children).

In our case there is no difference. It all goins in two steps:
1) first you filter events either by custom action handlers or by gesture detectors (like you've done with the scale one)
2) second you either call `dispatchTouchEvent` yourself or let the system call it for you (when `onInterceptTouchEvent` is used).

Either way children have no possibility to steal `any` event unless the parent allows it. The only possible case of stealing with `onInterceptTouchEvent` approach is the use of `requestDisallowInterceptTouchEvent`, but this case is very specific. 

PS:
> Your updated fix using a `OnTouchListener` still has the possibility of a child stealing Motion Events that are needed for the scale and scroll functionality.

I assume you meant `onInterceptTouchEvent` in conjunction with `onTouchEvent` here and not `OnTouchListener`.
